In [40]:
import pandas as pd
import numpy as np

In [41]:
df=pd.read_csv('tmdb_5000_movies.csv')
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [42]:
df_cred=pd.read_csv('tmdb_5000_credits.csv')
df_cred.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [43]:
df.rename(columns={'id' : 'movie_id'},inplace=True)
df.head(1)

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [44]:
df=pd.merge(df,df_cred,on='movie_id')
df.head(1)

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [45]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [46]:
df['original_language'].value_counts()

original_language
en    4505
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
cn      12
ru      11
ko      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ar       2
id       2
ro       2
te       1
xx       1
hu       1
is       1
tr       1
nb       1
af       1
pl       1
vi       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   movie_id              4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title_x               4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   str
 21  cast                  4803 non-null   str
 22  crew                  4803 non-null   str
dtypes: float64(3), int64(4), str(16)
memory usage: 39.2 MB

In [48]:
mov=df[['genres','movie_id','overview','release_date','title_x','cast','crew','keywords']]
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,A cryptic message from Bond’s past sends him o...,2015-10-26,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."

In [49]:
mov['release_date']

0       2009-12-10
1       2007-05-19
2       2015-10-26
3       2012-07-16
4       2012-03-07
           ...
4798    1992-09-04
4799    2011-12-26
4800    2013-10-13
4801    2012-05-03
4802    2005-08-05
Name: release_date, Length: 4803, dtype: str

In [50]:
mov['release_date']=mov['release_date'].fillna('0').apply(lambda x : int(str(x).split('-')[0]))

In [51]:
mov['release_date']=mov['release_date'].astype(int)
print(mov[mov['release_date']>0]['release_date'].min(),mov['release_date'].max())

1916 2017

In [52]:
def rel_gen(df,col) :
    bins = [1916, 1926, 1936, 1946, 1956, 1966, 1976,1986, 1996, 2006, 2016, 2018]
    label= [f"gen{i}" for i in range(1,12)]
    df[col]=pd.cut(
        df[col], bins=bins, labels=label, right=False
    ).astype('object').fillna('Other')
    return df[col]

In [53]:
mov['release_date']=rel_gen(mov,'release_date')

In [54]:
mov['release_date'].value_counts()

release_date
gen10    2247
gen9     1655
gen8      385
gen7      213
gen11     105
gen6       84
gen5       50
gen4       29
gen3       23
gen2        9
gen1        2
Other       1
Name: count, dtype: int64

In [55]:
mov[mov['release_date']=='Other']

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
4553,[],380097,1971 post civil rights San Francisco seemed li...,Other,America Is Still the Place,[],[],[]

In [56]:
mov['release_date']=mov['release_date'].replace({
    'Other': 'gen8',
    'gen1': 'gen3',
    'gen2': 'gen3',
    'gen3': 'gen4'
})

In [57]:
mov.isnull().sum()

genres          0
movie_id        0
overview        3
release_date    0
title_x         0
cast            0
crew            0
keywords        0
dtype: int64

In [58]:
mov.dropna(inplace=True)

In [59]:
mov.duplicated().sum()

np.int64(0)

In [60]:
mov.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [61]:
import ast

In [62]:
def cov_genres(x) :
    arr=[]
    for i in ast.literal_eval(x) :
        arr.append(i['name'])
    return arr

In [63]:
x=cov_genres(mov.iloc[0].genres)
x

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [64]:
mov['genres']=mov['genres'].apply(cov_genres)

In [65]:
mov['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4800, dtype: object

In [66]:
mov.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [67]:
def cov_cast(x) :
    obj=ast.literal_eval(x)
    L=[]
    for i in obj[:3] :
        L.append(i['character'])
    return L

In [68]:
mov['cast']=mov['cast'].apply(cov_cast)

In [69]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",gen10,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",gen10,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,gen10,Spectre,"[James Bond, Blofeld, Madeleine]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."

In [70]:
mov.iloc[2047].crew

'[{"credit_id": "536da61c0e0a2647d400eced", "department": "Sound", "gender": 2, "id": 19746, "job": "Music", "name": "Peter Bernstein"}, {"credit_id": "536da6360e0a2647c800f404", "department": "Crew", "gender": 0, "id": 52081, "job": "Cinematography", "name": "Albert J. Dunk"}, {"credit_id": "536da56c0e0a2647d800efa4", "department": "Writing", "gender": 2, "id": 65237, "job": "Writer", "name": "John Fasano"}, {"credit_id": "536da5860e0a2647d100ea06", "department": "Writing", "gender": 2, "id": 87432, "job": "Writer", "name": "Stephan Blinn"}, {"credit_id": "536da4e90e0a2647c400f1f4", "department": "Directing", "gender": 0, "id": 84981, "job": "Director", "name": "Brian Trenchard-Smith"}, {"credit_id": "536da5300e0a2647d400ecd0", "department": "Directing", "gender": 2, "id": 1318092, "job": "Director", "name": "Paul J. Lombardi"}, {"credit_id": "536da65f0e0a2647c800f409", "department": "Editing", "gender": 0, "id": 1318093, "job": "Editor", "name": "John Lafferty"}, {"credit_id": "578108a1c3a36843bf00085d", "department": "Crew", "gender": 1, "id": 1332245, "job": "Stunts", "name": "Nancy Young"}]'

In [71]:
def cov_crew(x) :
    obj=ast.literal_eval(x)
    L=[]
    for i in obj[:10] :
        if((i['job']=="Director") or i['job']=="Writer") :
            L.append(i['name'])
    return L

In [72]:
mov['crew']=mov['crew'].apply(cov_crew)

In [73]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",gen10,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[James Cameron, James Cameron]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",gen10,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,gen10,Spectre,"[James Bond, Blofeld, Madeleine]",[Sam Mendes],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."

In [74]:
mov.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [75]:
def cov_keywords(x) :
    L=[]
    obj=ast.literal_eval(x)
    for i in obj[:12] :
        L.append(i['name'])
    return L

In [76]:
mov['keywords']=mov['keywords'].apply(cov_keywords)

In [77]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"In the 22nd century, a paraplegic Marine is di...",gen10,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[James Cameron, James Cameron]","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"Captain Barbossa, long believed to be dead, ha...",gen10,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,A cryptic message from Bond’s past sends him o...,gen10,Spectre,"[James Bond, Blofeld, Madeleine]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi..."

In [78]:
mov['overview']=mov['overview'].apply(lambda x : x.replace(',','').replace('.','').replace('!','').split())

In [79]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[In, the, 22nd, century, a, paraplegic, Marine...",gen10,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[James Cameron, James Cameron]","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[Captain, Barbossa, long, believed, to, be, de...",gen10,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[A, cryptic, message, from, Bond’s, past, send...",gen10,Spectre,"[James Bond, Blofeld, Madeleine]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi..."

In [80]:
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
stopword=set(stopwords.words('english'))
stemer=PorterStemmer()

In [81]:
def normalizer(arr) : 
    output=[]
    for word in arr : 
        word=word.lower()
        if word not in stopword :
            output.append(stemer.stem(word))
    return output

In [82]:
mov['overview']=mov['overview'].apply(normalizer)

In [83]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[22nd, centuri, parapleg, marin, dispatch, moo...",gen10,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[James Cameron, James Cameron]","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[captain, barbossa, long, believ, dead, come, ...",gen10,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[cryptic, messag, bond’, past, send, trail, un...",gen10,Spectre,"[James Bond, Blofeld, Madeleine]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi..."

In [84]:
mov['release_date'] = mov['release_date'].apply(lambda x: [x])
mov['tags']=mov['overview']+mov['release_date']+mov['cast']+mov['crew']+mov['keywords']+mov['genres']

In [85]:
mov.head(3)

,genres,movie_id,overview,release_date,title_x,cast,crew,keywords,tags
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[22nd, centuri, parapleg, marin, dispatch, moo...",[gen10],Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine]","[James Cameron, James Cameron]","[culture clash, future, space war, space colon...","[22nd, centuri, parapleg, marin, dispatch, moo..."
1,"[Adventure, Fantasy, Action]",285,"[captain, barbossa, long, believ, dead, come, ...",[gen10],Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ...","[captain, barbossa, long, believ, dead, come, ..."
2,"[Action, Adventure, Crime]",206647,"[cryptic, messag, bond’, past, send, trail, un...",[gen10],Spectre,"[James Bond, Blofeld, Madeleine]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi...","[cryptic, messag, bond’, past, send, trail, un..."

In [86]:
dff=mov[['movie_id','title_x','tags']]
dff.head(3)

,movie_id,title_x,tags
0,19995,Avatar,"[22nd, centuri, parapleg, marin, dispatch, moo..."
1,285,Pirates of the Caribbean: At World's End,"[captain, barbossa, long, believ, dead, come, ..."
2,206647,Spectre,"[cryptic, messag, bond’, past, send, trail, un..."

In [87]:
dff['tags']=mov['tags'].replace(' ','')
dff['tags']=mov['tags'].apply(normalizer)
dff.head(3)

,movie_id,title_x,tags
0,19995,Avatar,"[22nd, centuri, parapleg, marin, dispatch, moo..."
1,285,Pirates of the Caribbean: At World's End,"[captain, barbossa, long, believ, dead, come, ..."
2,206647,Spectre,"[cryptic, messag, bond’, past, send, trail, un..."

In [88]:
dff['tags']=dff['tags'].apply(lambda x : ' '.join(x))
dff.head(3)

,movie_id,title_x,tags
0,19995,Avatar,22nd centuri parapleg marin dispatch moon pand...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believ dead come back li...
2,206647,Spectre,cryptic messag bond’ past send trail uncov sin...

In [89]:
from sklearn.feature_extraction.text import CountVectorizer 
cv=CountVectorizer(max_features=7500)

In [90]:
vector=cv.fit_transform(dff['tags']).toarray()

In [91]:
vector.shape

(4800, 7500)

In [92]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity.shape

(4800, 4800)

In [93]:
def recomend(name):
    matches = dff[dff['title_x'].str.contains(name, case=False, na=False)]
    if matches.empty:
        print("Movie not found!")
        return
    ind = matches.index[0]
    enu = list(enumerate(similarity[ind]))
    res = sorted(enu, reverse=True, key=lambda x: x[1])[1:6]
    for i in res:
        print(dff.iloc[i[0]]['title_x'])

In [94]:
recomend('avengers')

The Avengers
Iron Man
Iron Man 3
Iron Man 2
Captain America: Civil War

In [95]:
import pickle

In [96]:
pickle.dump(dff.to_dict(), open('data_set.pkl', 'wb'))
pickle.dump(similarity,open('similarity_set.pkl','wb'))